### ISSUE TITLE
Update example models so they work with the new next pointers that replace PCs

### ISSUE THREAD

**Issue by JoeyOhman** [miking-lang/miking-dppl#58]
The structure of models is slightly changed:

- `ADD_BBLOCK` is no longer needed
- `FIRST_BBLOCK` should be specified for the first bblock and `ADD_BBLOCK` is no longer required. 
- `INIT_MODEL` does no longer have the argument NUM_BBLOCKS, only `progState_t` (or no arguments in case of `INIT_MODEL_STACK`)
- `PC` macro is replaced with `NEXT` and holds a function pointer. See crbd for examples. 

All example models except crbd need to be adapted for this.

**Comment by dlunde** [comment]
I labeled this a "bug", since those models are technically not working right now.

**Comment by dlunde** [comment]
Now fixed in https://github.com/miking-lang/miking-dppl/pull/67, closing
